task:
  name: "Build Kernel"
  timeout_in: 60m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 6
      memory: 24G



  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - git clone --depth=1 https://gitlab.com/ElectroPerf/atom-x-clang.git ~/clang
      - export PATH="$PATH:$HOME/clang/bin"
      - git clone --depth=1 https://github.com/aospa-gauguin/kernel_xiaomi_gauguin ~/kernel

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/kernel
      - curl -fsSl https://gist.githubusercontent.com/DevAdalat/acc5babe30199c2e71aa3500efd14ef7/raw/b49e8c6a86e837b19f67f138483e48f1dc493e14/build.sh | bash
